print ('Digite a altura do degrau.')
degrau = float(input())
print ('Digite a altura que deseja alcançar, subindo a escada.')
altura = float(input())
quantidade = int(altura/degrau)
print ('Precisa subir',quantidade, 'de degraus.')
